### ISSUE TITLE
vagrant up does not work - no target name matches 'boxes.monsieurbiz.com'

### ISSUE THREAD

**Issue by TheSearcher** [monsieurbiz/vagrant-magento#2]
hi

i am using windows 8 .

i git cloned your deposit and then attempted to do a vagrant up

this is the error message i received: 

==> default: Adding box 'debian-wheezy' (v0) for provider: virtualbox
    default: Downloading: http://boxes.monsieurbiz.com/debian-wheezy.box
    default:
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

SSL: no alternative certificate subject name matches target host name 'boxes.monsieurbiz.com'

**Comment by jacquesbh** [comment]
Hi!

Yes, this project is not up to date.

You should avoid using it. Sorry for that.

Jacques Bodin-Hullin

-- 
Monsieur Biz <https://monsieurbiz.com>
@jacquesbh <https://twitter.com/jacquesbh>
+33 (0)6 75 54 11 97
GPG : https://keybase.io/jacquesbh

🦄

Le mar. 21 mars 2017 à 10:29, TheSearcher <notifications@github.com> a
écrit :

**Comment by TheSearcher** [comment]
thank for the update.

do you know any githubs for magento-vagrant that work. i am finding it very difficult to find somthing that works

**Comment by jacquesbh** [comment]
@TheSearcher 

You can use [Ansible as provisioner.](https://www.vagrantup.com/docs/provisioning/ansible.html)

You can find some roles very easy to setup here: https://galaxy.ansible.com/monsieurbiz/
Sorry the is no real documentation. Have a look to the `defaults/main.yml` file in each role.

If you are on Magento 2, have a look on the dev box: https://magento.com/blog/technical/set-your-magento-2-development-environment-faster
